// Generated by `tool/sign_manifest.dart` — do not edit manually.
//
// В production этот ключ заменяется на release-ключ (offline-secret
// pair, сгенерированная CI). В MVP используется throwaway
// test-ключ, привязанный только к локальному dev-серверу.
const String kManifestPublicKeyBase64 = '/PTJqraJ2pzY/RHR9Ap23ZPu9cFi4CY8ifNFZOhy4ac=';
