/// Чистый data-класс для результата парсинга seed-датасета.
///
/// Вынесен в отдельный файл без Flutter/Dio-зависимостей, чтобы
/// [SeedParser] можно было тестировать через `dart test` без
/// подтягивания всего pub-графа.
class ContentDownloadResult {
  const ContentDownloadResult({
    required this.surahs,
    required this.ayahs,
    required this.translations,
    required this.translators,
    this.words = const [],
  });

  final List<Map<String, dynamic>> surahs;
  final List<Map<String, dynamic>> ayahs;
  final List<Map<String, dynamic>> translations;
  final List<Map<String, dynamic>> translators;

  /// Per-word mushaf dictionary (Arabic, transliteration,
  /// translation, lemma, root). Populated from
  /// `assets/quran_seed/words.json` which is generated by
  /// `tools/build_words_seed.dart` and is optional — older seed
  /// files simply don't have the `words` key, and the bootstrap
  /// degrades gracefully (the table stays empty until someone
  /// re-runs the generator).
  final List<Map<String, dynamic>> words;
}
