// Генератор Ed25519 ключевой пары + подписанного manifest'а для
// тестирования `ContentUpdateService`. Запускается один раз:
//
//   dart run tool/sign_manifest.dart \
//     --version 1.1.0 \
//     --min-app 1.0.0 \
//     --payload assets/quran_seed/quran_full.json \
//     --out tool/signed \
//     --pub-out lib/core/content/_keys.dart
//
// Артефакты:
//   * `tool/signed/manifest.json` — подписанный манифест, готовый
//     к раздаче.
//   * `tool/signed/manifest.public.pem` — public key в PEM. **Это
//     вставляется в `lib/core/content/_keys.dart` через
//     `--pub-out`**, чтобы клиент мог верифицировать подпись.
//   * `tool/signed/payloads/quran-{version}.json` — payload
//     (копия, на которую ссылается manifest).
//
// После того, как файлы сгенерированы, поднимите локальный
// HTTP-сервер (см. `tool/serve_manifest.dart`) и запустите
// приложение с `--dart-define=QURAN MANIFEST BASE=http://10.0.2.2:8765/v1`.

import 'dart:convert';
import 'dart:io';

import 'package:args/args.dart';
import 'package:crypto/crypto.dart' as crypto;
import 'package:cryptography/cryptography.dart' as ed;

Future<void> main(List<String> args) async {
  final parser = ArgParser()
    ..addOption('version', abbr: 'v', mandatory: true)
    ..addOption('min-app', abbr: 'm', mandatory: true)
    ..addOption('payload', abbr: 'p', mandatory: true)
    ..addOption('out', abbr: 'o', mandatory: true)
    ..addOption('pub-out', mandatory: true);
  final results = parser.parse(args);

  final version = results['version'] as String;
  final minApp = results['min-app'] as String;
  final payloadPath = results['payload'] as String;
  final outDir = results['out'] as String;
  final pubOutPath = results['pub-out'] as String;

  // 1) Генерируем Ed25519 ключевую пару
  print('Generating Ed25519 keypair…');
  final algorithm = ed.Ed25519();
  final keyPair = await algorithm.newKeyPair();
  // `extractPublicKey()` и `extractPrivateKeyBytes()` возвращают
  // `Future<PublicKey>` / `Future<List<int>>` (cryptography 2.9
  // API). `bytes` getter'а у `PublicKey` есть, у `List<int>` —
  // нет (это и есть сам List).
  final publicKey = await keyPair.extractPublicKey();
  final publicKeyBytes = publicKey.bytes;
  final privateKeyBytes = await keyPair.extractPrivateKeyBytes();

  // 2) Считаем SHA256 payload'а
  print('Computing SHA256 of $payloadPath…');
  final payloadFile = File(payloadPath);
  if (!payloadFile.existsSync()) {
    stderr.writeln('Payload file not found: $payloadPath');
    exit(1);
  }
  final payloadBytes = await payloadFile.readAsBytes();
  final payloadSha = crypto.sha256.convert(payloadBytes).toString();

  // 3) Собираем manifest.json
  final manifest = {
    'content_version': version,
    'min_app_version': minApp,
    'payload_sha256': payloadSha,
    'editions': ['quran-uthmani'],
    'translations': [
      {'id': 1, 'name': 'Кулиев', 'language_code': 'ru', 'edition': 'ru.kuliev'},
      {'id': 2, 'name': 'Sahih International', 'language_code': 'en', 'edition': 'en.sahih'},
    ],
  };
  final manifestJson = jsonEncode(manifest);

  // 4) Подписываем `sha256(manifestJson)` через Ed25519
  final sha = crypto.sha256.convert(utf8.encode(manifestJson)).toString();
  print('Signing manifest sha256=$sha…');
  final signature = await algorithm.sign(
    utf8.encode(sha),
    keyPair: keyPair,
  );
  final signatureBase64 = base64Encode(signature.bytes);

  // 5) Записываем manifest.json с подписью
  final manifestWithSig = {
    ...manifest,
    'signature': signatureBase64,
  };
  // Нормализуем `outDir` (без trailing slash), чтобы
  // `File('$outDir/manifest.json')` не превратился в
  // `tool/signedmanifest.json`.
  final normalizedOut = outDir.endsWith('/') || outDir.endsWith(r'\')
      ? outDir.substring(0, outDir.length - 1)
      : outDir;
  final outDirectory = Directory(normalizedOut);
  if (!outDirectory.existsSync()) {
    await outDirectory.create(recursive: true);
  }
  final manifestOut = File('$normalizedOut/manifest.json');
  await manifestOut.writeAsString(
    const JsonEncoder.withIndent('  ').convert(manifestWithSig),
  );
  print('Wrote ${manifestOut.path}');

  // 6) Копируем payload в `payloads/quran-{version}.json`
  final payloadsDir = Directory('$normalizedOut/payloads');
  if (!payloadsDir.existsSync()) {
    await payloadsDir.create(recursive: true);
  }
  final payloadOut = File('${payloadsDir.path}/quran-$version.json');
  await payloadOut.writeAsBytes(payloadBytes);
  print('Wrote ${payloadOut.path}');

  // 7) Записываем public key в файл, который компилируется в APK
  // (через `--pub-out lib/core/content/_keys.dart`).
  final pubKeyB64 = base64Encode(publicKeyBytes);
  final pubKeyDart = '''
// Generated by `tool/sign_manifest.dart` — do not edit manually.
//
// В production этот ключ заменяется на release-ключ (offline-secret
// pair, сгенерированная CI). В MVP используется throwaway
// test-ключ, привязанный только к локальному dev-серверу.
const String kManifestPublicKeyBase64 = '$pubKeyB64';
''';
  final pubOut = File(pubOutPath);
  await pubOut.writeAsString(pubKeyDart);
  print('Wrote ${pubOut.path}');

  // 8) Для справки — закрытый ключ (НЕ коммитим)
  final privateKeyB64 = base64Encode(privateKeyBytes);
  print('\n=== Generated ===');
  print('Public  key: $pubKeyB64');
  print('Private key: $privateKeyB64  ⚠️  НЕ коммитить, только для локального dev');
  print('Payload  sha256: $payloadSha');
  print('Manifest sha256: $sha');
  print('Signature (base64): $signatureBase64');
  print('\nЧтобы протестировать локально:');
  print('  1. dart run tool/serve_manifest.dart --root tool/signed --port 8765');
  print('  2. flutter run -d <device> --dart-define=QURAN MANIFEST BASE=http://10.0.2.2:8765/v1');
  print('  3. (для Android emulator) или http://localhost:8765/v1 (для web/desktop)');
}
